
version: '3'

services:
  mysql_db:
    image: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=@Danggiap17
      - MYSQL_DATABASE=jwt
    ports:
      - "3306:3306"
    network_mode: host
    volumes:
      - database:/var/lib/docker/volumes/database/_data

  app_Noron :
    image: app_noron
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    network_mode: host
volumes:
  database :

