version: '3'

services:
  database_mysql:
    image: mysql_8.3
    container_name: database_noron
    environment:
      - MYSQL_ROOT_PASSWORD=@Danggiap17
      - MYSQL_DATABASE=jwt
    ports:
      - "3306:3306"
    network_mode: host
    volumes:
      - database_mysql:/var/lib/docker/volumes/database_mysql/_data
  noron_app:
    image: app_noron
    container_name: BE_app
    ports:
      - "8080:8080"
    depends_on:
      - database_mysql
    network_mode: host

volumes:
  database_mysql: