version: '3'

services:
  mysql1:
    image: database
    environment:
      MYSQL_ROOT_PASSWORD: "@Danggiap17"
      MYSQL_DATABASE: jwt
    network_mode: host
    volumes:
      - NoronBE:/var/lib/docker/volumes/NoronBE/_data
  noron1:
    image: app
    depends_on:
      - mysql1
    network_mode: host
volumes:
  NoronBE:


