
version: '3'

services:
  database_mysql:
    image: mysql_8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=@Danggiap17
      - MYSQL_DATABASE=jwt
    network_mode: host
    ports:
      - "3306:3306"
    volumes:
      - database_mysql:/var/lib/docker/volumes/database_mysql


  noron_be:
    image: app_noron
    ports:
      - "8080:8080"
    depends_on:
      - database_mysql
    network_mode: host

volumes:
  database_mysql: